layout_spectrum: 0.6003147
typography_spectrum: 0.236689
color:
  saturation: 0.8649244
  lightness: 0.3112732
  brandStrength: 0.04889153
  rhythmicContrast: 0.1566783
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: aroundlouisvilleky
